### ISSUE TITLE
Not working at all since first attempt

### ISSUE THREAD

**Issue by Sephirothbahamut** [ReBuilders101/CellPacker#3]
Edit: maybe it would be nice to specify the software requires 64bit version of java 
___________________
Running CellPacker.jar opens what i think is the "editor" window, not the launcher. No backup file or folder was created the first time. Nor the editor can open res.pak. Just nothing happens.

On a 32bit version it could use some splitting to load resources by request so it's slower but saves memory. I'm not a java kind of person so i've no idea if there is something like C++'s ifdef/endif to do that.
___________________
This is the error output i get running from prompt:
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at dev.lb.cellpacker.structure.ResourceFile.fromFile(ResourceFile.java:92)
	at dev.lb.cellpacker.controls.MainWindow.lambda$0(MainWindow.java:94)
	at dev.lb.cellpacker.controls.MainWindow$$Lambda$10/5326611.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)

**Comment by JamesF22293** [comment]
I'm also having this problem. Any fix would be welcome. Issue is present in a java 9 runtime environment, with Windows 10 home OS installed.

**Comment by raeneau** [comment]
I'm late to the party, just got interested in the game, found this repo, etc etc. Try running java with more memory:
`java -Xmx2048m -jar CellPacker.jar`
I've tried lower mem amounts but 2048 seems to do the trick and I can open the res.pak

**Comment by changbowen** [comment]
I can get it to save without throwing that error using `java -Xmx12288m -jar CellPacker.jar` but game won't load after that even nothing is modified, throwing something like `Resource file not found 'atlas/beheadedCollectorR5.atlas'`
